"""
Mail Scheduler for Automatic Daily Attendance Email

This script automatically sends daily attendance reports by email.
Use with Windows Task Scheduler or cron jobs.

Setup:
1. Configure environment variables or .env file:
   - SENDER_EMAIL
   - SENDER_PASSWORD
   - RECIPIENT_EMAIL
   - SMTP_SERVER (optional, default: smtp.gmail.com)
   - SMTP_PORT (optional, default: 587)

2. For Windows Task Scheduler:
   - Run: python mail_scheduler.py
   - Schedule to run daily at your preferred time

3. For Linux/Mac cron:
   - Add to crontab: 0 17 * * * cd /path/to/attendance && python mail_scheduler.py
"""

import os
import sys
import pandas as pd
import smtplib
from datetime import datetime, timedelta
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from pathlib import Path

def load_config():
    """Load configuration from environment variables or .env file"""
    # Try to load from .env file
    env_file = Path('.env')
    if env_file.exists():
        with open(env_file) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#'):
                    key, value = line.split('=', 1)
                    os.environ[key.strip()] = value.strip()
    
    config = {
        'sender_email': os.getenv('SENDER_EMAIL', ''),
        'sender_password': os.getenv('SENDER_PASSWORD', ''),
        'recipient_email': os.getenv('RECIPIENT_EMAIL', ''),
        'smtp_server': os.getenv('SMTP_SERVER', 'smtp.gmail.com'),
        'smtp_port': int(os.getenv('SMTP_PORT', '587'))
    }
    
    return config

def send_daily_attendance_email():
    """Send today's attendance report via email"""
    
    config = load_config()
    
    # Validate configuration
    if not all([config['sender_email'], config['sender_password'], config['recipient_email']]):
        print("❌ Error: Missing email configuration")
        print("Please set SENDER_EMAIL, SENDER_PASSWORD, and RECIPIENT_EMAIL environment variables")
        return False
    
    # Get today's date and attendance file
    today = datetime.now().strftime('%Y-%m-%d')
    attendance_file = f'attendance_{today}.csv'
    
    # Check if attendance file exists
    if not os.path.exists(attendance_file):
        print(f"⚠️  No attendance file found for {today}")
        return False
    
    try:
        # Read attendance file
        df = pd.read_csv(attendance_file)
        
        if df.empty:
            print(f"ℹ️  No attendance records for {today}")
            return False
        
        csv_data = df.to_csv(index=False)
        
        # Create email
        message = MIMEMultipart()
        message['From'] = config['sender_email']
        message['To'] = config['recipient_email']
        message['Subject'] = f"Daily Attendance Report - {today}"
        
        # Email body
        body = f"""
Daily Attendance Report
Date: {today}
Total Records: {len(df)}
Unique People: {df['Name'].nunique()}

In-Time Marked: {df['In-Time'].ne('NA').sum()}
Out-Time Marked: {df['Out-Time'].ne('NA').sum()}

Please find the detailed report attached.

Generated by Attendance System
{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
        """
        
        message.attach(MIMEText(body, 'plain'))
        
        # Attach CSV
        attachment = MIMEBase('application', 'octet-stream')
        attachment.set_payload(csv_data.encode())
        encoders.encode_base64(attachment)
        attachment.add_header('Content-Disposition', f'attachment; filename= {attendance_file}')
        message.attach(attachment)
        
        # Send email
        with smtplib.SMTP(config['smtp_server'], config['smtp_port']) as server:
            server.starttls()
            server.login(config['sender_email'], config['sender_password'])
            server.send_message(message)
        
        print(f"✅ Daily attendance email sent successfully for {today}")
        print(f"   Recipient: {config['recipient_email']}")
        print(f"   Records: {len(df)}")
        return True
    
    except smtplib.SMTPAuthenticationError:
        print("❌ Email authentication failed. Check your credentials.")
        return False
    except smtplib.SMTPException as e:
        print(f"❌ SMTP error: {str(e)}")
        return False
    except Exception as e:
        print(f"❌ Error: {str(e)}")
        return False

def send_monthly_attendance_email():
    """Send monthly attendance report via email"""
    
    config = load_config()
    
    # Validate configuration
    if not all([config['sender_email'], config['sender_password'], config['recipient_email']]):
        print("❌ Error: Missing email configuration")
        return False
    
    try:
        # Get last month's data
        today = datetime.now()
        if today.day == 1:
            # If today is the 1st, send last month's report
            last_day_last_month = today - timedelta(days=1)
        else:
            # Otherwise get last day of current month
            last_day_last_month = today
        
        year = last_day_last_month.year
        month = last_day_last_month.month
        
        # Collect monthly data
        from calendar import monthrange
        num_days = monthrange(year, month)[1]
        monthly_data = {}
        all_people = set()
        
        for day in range(1, num_days + 1):
            date_str = f"{year:04d}-{month:02d}-{day:02d}"
            attendance_file = f"attendance_{date_str}.csv"
            
            if os.path.exists(attendance_file):
                df_temp = pd.read_csv(attendance_file)
                for _, row in df_temp.iterrows():
                    name = row['Name']
                    all_people.add(name)
                    if name not in monthly_data:
                        monthly_data[name] = {'present_dates': [], 'absent_dates': []}
                    monthly_data[name]['present_dates'].append(date_str)
        
        # Calculate absent dates
        for day in range(1, num_days + 1):
            date_str = f"{year:04d}-{month:02d}-{day:02d}"
            for person in all_people:
                if person not in monthly_data:
                    monthly_data[person] = {'present_dates': [], 'absent_dates': []}
                if date_str not in monthly_data[person]['present_dates']:
                    monthly_data[person]['absent_dates'].append(date_str)
        
        if not monthly_data:
            print(f"ℹ️  No attendance records for the month")
            return False
        
        # Create DataFrame
        summary_list = []
        for name in sorted(monthly_data.keys()):
            data = monthly_data[name]
            absent_str = ', '.join(sorted(data['absent_dates'])) if data['absent_dates'] else 'No absences'
            summary_list.append({
                'Name': name,
                'Days Present': len(data['present_dates']),
                'Absent Dates': absent_str
            })
        
        df_monthly = pd.DataFrame(summary_list)
        csv_data = df_monthly.to_csv(index=False)
        
        # Create email
        message = MIMEMultipart()
        message['From'] = config['sender_email']
        message['To'] = config['recipient_email']
        message['Subject'] = f"Monthly Attendance Report - {datetime(year, month, 1).strftime('%B %Y')}"
        
        body = f"""
Monthly Attendance Report
Period: {datetime(year, month, 1).strftime('%B %Y')}
Total People: {len(df_monthly)}
Total Person-Days: {df_monthly['Days Present'].sum()}
Average Days Present: {df_monthly['Days Present'].mean():.1f}

Please find the detailed report attached.

Generated by Attendance System
{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
        """
        
        message.attach(MIMEText(body, 'plain'))
        
        # Attach CSV
        filename = f"monthly_attendance_{year:04d}-{month:02d}.csv"
        attachment = MIMEBase('application', 'octet-stream')
        attachment.set_payload(csv_data.encode())
        encoders.encode_base64(attachment)
        attachment.add_header('Content-Disposition', f'attachment; filename= {filename}')
        message.attach(attachment)
        
        # Send email
        with smtplib.SMTP(config['smtp_server'], config['smtp_port']) as server:
            server.starttls()
            server.login(config['sender_email'], config['sender_password'])
            server.send_message(message)
        
        print(f"✅ Monthly attendance email sent successfully")
        print(f"   Period: {datetime(year, month, 1).strftime('%B %Y')}")
        print(f"   Recipient: {config['recipient_email']}")
        return True
    
    except Exception as e:
        print(f"❌ Error: {str(e)}")
        return False

if __name__ == '__main__':
    import argparse
    
    parser = argparse.ArgumentParser(description='Send attendance reports via email')
    parser.add_argument('--type', choices=['daily', 'monthly'], default='daily',
                       help='Type of report to send (daily or monthly)')
    
    args = parser.parse_args()
    
    print(f"Sending {args.type} attendance report...")
    
    if args.type == 'daily':
        success = send_daily_attendance_email()
    else:
        success = send_monthly_attendance_email()
    
    sys.exit(0 if success else 1)
